variable "project" {}
variable "region" {}
variable "zone" {}
variable "api_key" {}
variable "app_key" {}
variable "api_url" {}
variable "name" {}
variable "default_machine_type" {}
variable "image" {}